export const ADD_COPY_ITEM = 'ADD_COPY_ITEM';
export const DELETE_COPY_ITEM = 'DELETE_COPY_ITEM';
export const EMPTY_COPY_ITEMS = 'EMPTY_COPY_ITEMS';
export const CHANGE_CURRENT_SOURCE_FOLDER = 'CHANGE_CURRENT_SOURCE_FOLDER';
export const CHANGE_CURRENT_TARGET_FOLDER = 'CHANGE_CURRENT_TARGET_FOLDER';

