export const ADD_COPY_ITEM = 'ADD_COPY_ITEM';
export const DELETE_COPY_ITEM = 'DELETE_COPY_ITEM';
export const EMPTY_COPY_ITEMS = 'EMPTY_COPY_ITEMS';
export const CHANGE_CURRENT_SOURCE_FOLDER = 'CHANGE_CURRENT_SOURCE_FOLDER';
export const CHANGE_CURRENT_TARGET_FOLDER = 'CHANGE_CURRENT_TARGET_FOLDER';
export const COPY_ALL_ITEMS_IS_ACTIVE = 'COPY_ALL_ITEMS_IS_ACTIVE';
export const COPY_ALL_ITEMS_IS_NOT_ACTIVE = 'COPY_ALL_ITEMS_IS_NOT_ACTIVE';

